---
title: "Assignment05"
author: "Steph Glatch"
date: "9/19/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
read_csv("C:/Users/Steph/Downloads/DSCI301/COVID_DATASET.csv")
```


# Problem 1

```{r}
library(tidyverse)
library(here)
co_data <- here("COVID_DATASET.csv")
```

```{r}
covid_data <- read_csv("C:/Users/Steph/Downloads/DSCI301/COVID_DATASET.csv",
                       col_types = 
                         cols(
                           `location` = col_character(),
                           `country` = col_character(),
                           `gender` = col_character(),
                           `age` = col_number()
                         ))
df <- covid_data[-c(4, 22:27)]
```

I decided to drop these particular columns because they only had "NA's" in them. Then I changed the column types to read the data that was given. 

# Problem 2

```{r}
covid_data %>%
  summarize(
    count = n(),
    mean_age = mean(age, na.rm = TRUE),
    sd_age = sd(age, na.rm = TRUE),
    median_age = median(age, na.rm = TRUE), 
    range_age = range(age, na.rm = TRUE)
      )
```
The range goes from a 3 month old child to a 96 year old elderly. 


```{r}
covid_data %>%
    ggplot() +
    geom_histogram(aes(x = age))

ggplot(data = covid_data) +
  geom_bar(mapping = aes(x = gender))
```

```{r}
covid_data$country
```
Do count of country after 

# Problem 3

Distribution by gender and age
```{r}
covid_data %>%
    filter(gender != "-") %>%
    group_by(gender) %>%
    filter(n() > 5) %>%
    ungroup() %>%
    filter(!is.na(age)) %>%
    ggplot() +
        geom_boxplot(aes(x = gender, y = age)) + 
        coord_flip()
```

